
logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: warn
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: '1234'
    username: 'root'
    url: jdbc:mysql://localhost:3306/datingapp?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false

cloudinary:
  api-key: 838182148315422
  api-secret: 351352
  cloud-name: dit8nlten

schedulers:
  cron: "0 0 12 1 * ?"
  cron1: "0 0 */12 ? * *"
